// <auto-generated />
using System;
using EBS.RepositoryLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EBS.RepositoryLayer.Migrations
{
    [DbContext(typeof(EBSDBContext))]
    partial class EBSDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EBS.DomainLayer.Models.Admin", b =>
                {
                    b.Property<int>("admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("admin_Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("admin_Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("admin_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("admin_id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("EBS.DomainLayer.Models.Bill", b =>
                {
                    b.Property<int>("bill_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("bill_amount")
                        .HasColumnType("real");

                    b.Property<int>("bill_customerid")
                        .HasColumnType("int");

                    b.Property<float>("bill_energy_charge")
                        .HasColumnType("real");

                    b.Property<DateTime>("bill_issuedate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("bill_payingdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("bill_paymentMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("bill_present_reading")
                        .HasColumnType("real");

                    b.Property<float>("bill_previous_reading")
                        .HasColumnType("real");

                    b.Property<string>("bill_status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bill_id");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("EBS.DomainLayer.Models.Customer", b =>
                {
                    b.Property<int>("customer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("customer_Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("customer_id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("EBS.DomainLayer.Models.Payment", b =>
                {
                    b.Property<int>("payment_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("bill_energy_charge")
                        .HasColumnType("real");

                    b.Property<float>("bill_previous_reading")
                        .HasColumnType("real");

                    b.Property<float>("consumption_unit")
                        .HasColumnType("real");

                    b.Property<float>("payment_amount")
                        .HasColumnType("real");

                    b.Property<float>("payment_billamount")
                        .HasColumnType("real");

                    b.Property<int>("payment_billno")
                        .HasColumnType("int");

                    b.Property<int>("payment_customerid")
                        .HasColumnType("int");

                    b.Property<DateTime>("payment_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("payment_issuedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("payment_mode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("payment_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("payment_tax")
                        .HasColumnType("real");

                    b.HasKey("payment_no");

                    b.ToTable("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
